# Generated by Django 5.1.6 on 2025-02-12 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.aluno')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.horario')),
            ],
        ),
    ]
