# Generated by Django 5.1.6 on 2025-02-12 14:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_presenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(default='aluno@email.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='forma_pagamento',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('por_aula', 'Por Aula')], default='mensal', max_length=10),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now)),
                ('quantidade_aulas_pagas', models.IntegerField(default=0)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.aluno')),
            ],
        ),
    ]
