# Generated by Django 5.1.6 on 2025-02-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0003_aluno_email_aluno_forma_pagamento_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presenca',
            name='presente',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
    ]
